version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cartransfer-postgres
    environment:
      POSTGRES_USER: caruser
      POSTGRES_PASSWORD: carpassword
      POSTGRES_DB: cartransferdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
